#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label spotify
yabai -m space 4 --label slack
yabai -m space 5 --label social
yabai -m space 5 --label social

# window rules
yabai -m rule --add app="^kitty$" space=code
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Spotify$" space=spotify
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Discord$" space=social
yabai -m rule --add app="^Signal$" space=social
yabai -m rule --add app="^Messages$" space=social
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off
yabai -m rule --add app="^mpv$" manage=off border=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# global settings

yabai -m config                              \
    external_bar                all:40:0      \
    mouse_follows_focus         on           \
    focus_follows_mouse         autoraise    \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               off          \
    window_animation_duration   0.20         \
    window_opacity_duration     0.20         \
    active_window_opacity       1.00         \
    normal_window_opacity       0.80         \
    active_window_border_color  0xffe5e5e5   \
    normal_window_border_color  0xff444444   \
    window_opacity              on           \
    window_border_radius        8            \
    window_border_blur          on           \
    window_border_hidpi         on           \
    window_border_width         2            \
    window_border               on           \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 10           \
    left_padding                10           \
    right_padding               10           \
    bottom_padding              10           \
    window_gap                  10           \
    layout                      bsp          \
    mouse_modifier              fn           \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap

echo "yabai configuration loaded.."
